-- Highlight groups configuration
later(function()
	vim.cmd([[
    highlight clear
    syntax reset
  ]])
	local colors = {
		transparent = "NONE",
		silver = "#b2b2b2",
		brown = "#765341",
		black = "#1c1c1c",
		cement = "#7b8496",
		light_grey = "#2c2e33",
		white = "#ffffff",
		grey = "#3c4048",
		red = "#d75f5f",
		green = "#5f8700",
		blue = "#5f87d7",
		yellow = "#af8700",
		cyan = "#5fd7ff",
		pink = "#d75faf",
		dark_cyan = "#00af87",
		turquiose = "#008787",
		magenta = "#af005f",
		peach = "#ff5f87",
		orange = "#d78700",
		purple = "#af5fff",
		violet = "#d787ff",
	}
	local highlights = {
		-- Default highlights
		["ColorColumn"] = { bg = colors.light_grey },
		["Conceal"] = { fg = colors.green },
		["CurSearch"] = { bg = colors.silver, fg = colors.black },
		["Cursor"] = { bg = colors.white, fg = colors.black },
		["CursorColumn"] = { bg = colors.light_grey },
		["CursorIM"] = { bg = colors.white, fg = colors.black },
		["CursorLine"] = { bg = colors.light_grey },
		["CursorLineFold"] = { link = "CursorLineNr" },
		["CursorLineNr"] = { bg = colors.transparent, fg = colors.silver },
		["CursorLineSign"] = { link = "CursorLineNr" },
		["DiffAdd"] = { fg = colors.green },
		["DiffChange"] = { fg = colors.blue },
		["DiffDelete"] = { fg = colors.red },
		["DiffText"] = { bg = colors.turquiose, fg = colors.black },
		["Directory"] = { fg = colors.blue },
		["EndOfBuffer"] = { fg = colors.grey },
		["ErrorMsg"] = { fg = colors.red },
		["FloatBorder"] = { fg = colors.grey },
		["FloatFooter"] = { fg = colors.silver },
		["FloatTitle"] = { fg = colors.silver },
		["FoldColumn"] = { link = "LineNr" },
		["Folded"] = { fg = colors.silver, bg = colors.light_grey },
		["IncSearch"] = { bg = colors.grey },
		["LineNr"] = { bg = colors.transparent, fg = colors.grey },
		["LineNrAbove"] = { link = "LineNr" },
		["LineNrBelow"] = { link = "LineNr" },
		["MatchParen"] = { bg = colors.silver, fg = colors.black },
		["ModeMsg"] = { fg = colors.turquiose },
		["MoreMsg"] = { fg = colors.turquiose },
		["MsgArea"] = { bg = colors.transparent },
		["MsgSeparator"] = { bg = colors.turquiose, fg = colors.black },
		["NonText"] = { fg = colors.grey },
		["Normal"] = { bg = colors.transparent, fg = colors.cement },
		["NormalFloat"] = { bg = colors.transparent, fg = colors.silver },
		["NormalNC"] = { bg = colors.transparent, fg = colors.grey },
		["Pmenu"] = { bg = colors.transparent, fg = colors.grey },
		["PmenuExtra"] = { bg = colors.transparent, fg = colors.grey },
		["PmenuExtraSel"] = { bg = colors.light_grey, fg = colors.turquiose },
		["PmenuKind"] = { bg = colors.transparent, fg = colors.turquiose },
		["PmenuKindSel"] = { bg = colors.light_grey, fg = colors.turquiose },
		["PmenuMatch"] = { bg = colors.transparent, fg = colors.turquiose },
		["PmenuMatchSel"] = { bg = colors.light_grey, fg = colors.turquiose },
		["PmenuSbar"] = { bg = colors.transparent, fg = colors.grey },
		["PmenuSel"] = { bg = colors.light_grey, fg = colors.turquiose },
		["PmenuThumb"] = { bg = colors.grey },
		["Question"] = { fg = colors.turquiose },
		["QuickFixLine"] = { bg = colors.light_grey },
		["Search"] = { bg = colors.grey },
		["SignColumn"] = { link = "LineNr" },
		["SnippetTabstop"] = { fg = colors.turquiose },
		["SpecialKey"] = { fg = colors.grey },
		["SpellBad"] = { fg = colors.red },
		["SpellCap"] = { fg = colors.orange },
		["SpellLocal"] = { fg = colors.yellow },
		["SpellRare"] = { fg = colors.pink },
		["StatusLine"] = { bg = colors.transparent },
		["StatusLineNC"] = { bg = colors.transparent },
		["StatusLineTerm"] = { bg = colors.transparent },
		["StatusLineTermNC"] = { bg = colors.transparent },
		["Substitute"] = { bg = colors.grey },
		["TabLine"] = { bg = colors.light_grey },
		["TabLineFill"] = { bg = colors.grey },
		["TabLineSel"] = { bg = colors.transparent, fg = colors.turquiose },
		["TermCursor"] = { link = "Cursor" },
		["TermCursorNC"] = { link = "Cursor" },
		["Title"] = { fg = colors.turquiose },
		["Visual"] = { bg = colors.grey },
		["VisualNOS"] = { bg = colors.grey },
		["WarningMsg"] = { fg = colors.orange },
		["Whitespace"] = { fg = colors.grey },
		["WildMenu"] = { bg = colors.light_grey, fg = colors.turquiose },
		["WinBar"] = { bg = colors.light_grey },
		["WinBarNC"] = { bg = colors.transparent },
		["WinSeparator"] = { bg = colors.transparent, fg = colors.silver },
		["lCursor"] = { link = "Cursor" },
		-- Default syntax highlights
		["Added"] = { link = "DiffAdd" },
		["Boolean"] = { fg = colors.orange },
		["Changed"] = { link = "DiffChange" },
		["Character"] = { fg = colors.orange },
		["Comment"] = { fg = colors.grey, italic = true },
		["Conditional"] = { fg = colors.blue },
		["Constant"] = { fg = colors.orange },
		["Debug"] = { fg = colors.peach },
		["Define"] = { fg = colors.purple },
		["Delimiter"] = { fg = colors.magenta },
		["Error"] = { fg = colors.red },
		["Exception"] = { fg = colors.blue },
		["Float"] = { fg = colors.orange },
		["Function"] = { fg = colors.blue },
		["Identifier"] = { fg = colors.pink },
		["Ignore"] = { fg = colors.grey },
		["Include"] = { fg = colors.purple },
		["Keyword"] = { fg = colors.blue },
		["Label"] = { fg = colors.blue },
		["Macro"] = { link = "Define" },
		["Number"] = { fg = colors.orange },
		["Operator"] = { fg = colors.violet },
		["PreCondit"] = { fg = colors.blue },
		["PreProc"] = { fg = colors.violet },
		["Removed"] = { link = "DiffDelete" },
		["Repeat"] = { fg = colors.blue },
		["Special"] = { fg = colors.orange },
		["SpecialChar"] = { fg = colors.orange },
		["SpecialComment"] = { fg = colors.orange },
		["Statement"] = { fg = colors.purple },
		["StorageClass"] = { fg = colors.purple },
		["String"] = { fg = colors.dark_cyan },
		["Structure"] = { fg = colors.magenta },
		["Tag"] = { fg = colors.magenta },
		["Todo"] = { fg = colors.green },
		["Type"] = { fg = colors.orange },
		["Typedef"] = { fg = colors.pink },
		["Underlined"] = { underline = true },
		-- Mini highlights
		["MiniAnimateCursor"] = {},
		["MiniAnimateNormalFloat"] = {},
		["MiniClueBorder"] = {},
		["MiniClueDescGroup"] = {},
		["MiniClueDescSingle"] = {},
		["MiniClueNextKey"] = {},
		["MiniClueNextKeyWithPostkeys"] = {},
		["MiniClueSeparator"] = {},
		["MiniClueTitle"] = {},
		["MiniCompletionActiveParameter"] = {},
		["MiniCursorword"] = {},
		["MiniCursorwordCurrent"] = {},
		["MiniDepsChangeAdded"] = {},
		["MiniDepsChangeRemoved"] = {},
		["MiniDepsHint"] = {},
		["MiniDepsInfo"] = {},
		["MiniDepsMsgBreaking"] = {},
		["MiniDepsPlaceholder"] = {},
		["MiniDepsTitle"] = {},
		["MiniDepsTitleError"] = {},
		["MiniDepsTitleSame"] = {},
		["MiniDepsTitleUpdate"] = {},
		["MiniDiffOverAdd"] = {},
		["MiniDiffOverChange"] = {},
		["MiniDiffOverContext"] = {},
		["MiniDiffOverDelete"] = {},
		["MiniDiffSignAdd"] = {},
		["MiniDiffSignChange"] = {},
		["MiniDiffSignDelete"] = {},
		["MiniFilesBorder"] = {},
		["MiniFilesBorderModified"] = {},
		["MiniFilesCursorLine"] = {},
		["MiniFilesDirectory"] = {},
		["MiniFilesFile"] = {},
		["MiniFilesNormal"] = {},
		["MiniFilesTitle"] = {},
		["MiniFilesTitleFocused"] = {},
		["MiniHipatternsFixme"] = {},
		["MiniHipatternsHack"] = {},
		["MiniHipatternsNote"] = {},
		["MiniHipatternsTodo"] = {},
		["MiniIndentscopeSymbol"] = {},
		["MiniIndentscopeSymbolOff"] = {},
		["MiniJump"] = {},
		["MiniJump2dDim"] = {},
		["MiniJump2dSpot"] = {},
		["MiniJump2dSpotAhead"] = {},
		["MiniJump2dSpotUnique"] = {},
		["MiniMapNormal"] = {},
		["MiniMapSymbolCount"] = {},
		["MiniMapSymbolLine"] = {},
		["MiniMapSymbolView"] = {},
		["MiniNotifyBorder"] = {},
		["MiniNotifyNormal"] = {},
		["MiniNotifyTitle"] = {},
		["MiniOperatorsExchangeFrom"] = {},
		["MiniPickBorder"] = {},
		["MiniPickBorderBusy"] = {},
		["MiniPickBorderText"] = {},
		["MiniPickHeader"] = {},
		["MiniPickIconDirectory"] = {},
		["MiniPickIconFile"] = {},
		["MiniPickMatchCurrent"] = {},
		["MiniPickMatchMarked"] = {},
		["MiniPickMatchRanges"] = {},
		["MiniPickNormal"] = {},
		["MiniPickPreviewLine"] = {},
		["MiniPickPreviewRegion"] = {},
		["MiniPickPrompt"] = {},
		["MiniStarterCurrent"] = {},
		["MiniStarterFooter"] = {},
		["MiniStarterHeader"] = {},
		["MiniStarterInactive"] = {},
		["MiniStarterItem"] = {},
		["MiniStarterItemBullet"] = {},
		["MiniStarterItemPrefix"] = {},
		["MiniStarterQuery"] = {},
		["MiniStarterSection"] = {},
		["MiniStatuslineDevinfo"] = {},
		["MiniStatuslineFileinfo"] = {},
		["MiniStatuslineFilename"] = {},
		["MiniStatuslineInactive"] = {},
		["MiniStatuslineModeCommand"] = {},
		["MiniStatuslineModeInsert"] = {},
		["MiniStatuslineModeNormal"] = {},
		["MiniStatuslineModeOther"] = {},
		["MiniStatuslineModeReplace"] = {},
		["MiniStatuslineModeVisual"] = {},
		["MiniSurround"] = {},
		["MiniTablineCurrent"] = {},
		["MiniTablineFill"] = {},
		["MiniTablineHidden"] = {},
		["MiniTablineModifiedCurrent"] = {},
		["MiniTablineModifiedHidden"] = {},
		["MiniTablineModifiedVisible"] = {},
		["MiniTablineTabpagesection"] = {},
		["MiniTablineVisible"] = {},
		["MiniTestEmphasis"] = {},
		["MiniTestFail"] = {},
		["MiniTestPass"] = {},
		["MiniTrailspace"] = {},
		-- Diagnostics highlights
		["DiagnosticError"] = {},
		["DiagnosticWarn"] = {},
		["DiagnosticInfo"] = {},
		["DiagnosticHint"] = {},
		["DiagnosticOk"] = {},
		["DiagnosticVirtualTextError"] = {},
		["DiagnosticVirtualTextWarn"] = {},
		["DiagnosticVirtualTextInfo"] = {},
		["DiagnosticVirtualTextHint"] = {},
		["DiagnosticVirtualTextOk"] = {},
		["DiagnosticUnderlineError"] = {},
		["DiagnosticUnderlineWarn"] = {},
		["DiagnosticUnderlineInfo"] = {},
		["DiagnosticUnderlineHint"] = {},
		["DiagnosticUnderlineOk"] = {},
		["DiagnosticFloatingError"] = {},
		["DiagnosticFloatingWarn"] = {},
		["DiagnosticFloatingInfo"] = {},
		["DiagnosticFloatingHint"] = {},
		["DiagnosticFloatingOk"] = {},
		["DiagnosticSignError"] = {},
		["DiagnosticSignWarn"] = {},
		["DiagnosticSignInfo"] = {},
		["DiagnosticSignHint"] = {},
		["DiagnosticSignOk"] = {},
		["DiagnosticDeprecated"] = {},
		["DiagnosticUnnecessary"] = {},
		-- Lsp highlights
		["LspCodeLens"] = {},
		["LspCodeLensSeparator"] = {},
		["LspInlayHint"] = { fg = colors.brown },
		["LspReferenceRead"] = {},
		["LspReferenceText"] = {},
		["LspReferenceWrite"] = {},
		["LspSignatureActiveParameter"] = {},
		-- Lsp semantic highlights
		["@lsp.mod.abstract"] = {},
		["@lsp.mod.async"] = {},
		["@lsp.mod.declaration"] = {},
		["@lsp.mod.defaultLibrary"] = {},
		["@lsp.mod.definition"] = {},
		["@lsp.mod.deprecated"] = {},
		["@lsp.mod.documentation"] = {},
		["@lsp.mod.modification"] = {},
		["@lsp.mod.readonly"] = {},
		["@lsp.mod.static"] = {},
		["@lsp.type.class"] = {},
		["@lsp.type.comment"] = {},
		["@lsp.type.decorator"] = {},
		["@lsp.type.enum"] = {},
		["@lsp.type.enumMember"] = {},
		["@lsp.type.event"] = {},
		["@lsp.type.function"] = {},
		["@lsp.type.interface"] = {},
		["@lsp.type.keyword"] = {},
		["@lsp.type.macro"] = {},
		["@lsp.type.method"] = {},
		["@lsp.type.modifier"] = {},
		["@lsp.type.namespace"] = {},
		["@lsp.type.number"] = {},
		["@lsp.type.operator"] = {},
		["@lsp.type.parameter"] = {},
		["@lsp.type.property"] = {},
		["@lsp.type.regexp"] = {},
		["@lsp.type.string"] = {},
		["@lsp.type.struct"] = {},
		["@lsp.type.type"] = {},
		["@lsp.type.typeParameter"] = {},
		["@lsp.type.variable"] = {},
		-- Treesitter highlights
		["@attribute"] = {},
		["@attribute.builtin"] = {},
		["@boolean"] = {},
		["@character"] = {},
		["@character.special"] = {},
		["@comment"] = {},
		["@comment.documentation"] = {},
		["@comment.error"] = {},
		["@comment.note"] = {},
		["@comment.todo"] = {},
		["@comment.warning"] = {},
		["@constant"] = {},
		["@constant.builtin"] = {},
		["@constant.macro"] = {},
		["@constructor"] = {},
		["@diff.delta"] = {},
		["@diff.minus"] = {},
		["@diff.plus"] = {},
		["@function"] = {},
		["@function.builtin"] = {},
		["@function.call"] = { link = "Function" },
		["@function.macro"] = {},
		["@function.method"] = {},
		["@function.method.call"] = {},
		["@keyword"] = {},
		["@keyword.conditional"] = {},
		["@keyword.conditional.ternary"] = {},
		["@keyword.coroutine"] = {},
		["@keyword.debug"] = {},
		["@keyword.directive"] = {},
		["@keyword.directive.define"] = {},
		["@keyword.exception"] = {},
		["@keyword.function"] = {},
		["@keyword.import"] = {},
		["@keyword.modifier"] = {},
		["@keyword.operator"] = {},
		["@keyword.repeat"] = {},
		["@keyword.return"] = {},
		["@keyword.type"] = {},
		["@label"] = {},
		["@markup.heading"] = {},
		["@markup.heading.1"] = {},
		["@markup.heading.2"] = {},
		["@markup.heading.3"] = {},
		["@markup.heading.4"] = {},
		["@markup.heading.5"] = {},
		["@markup.heading.6"] = {},
		["@markup.italic"] = {},
		["@markup.link"] = {},
		["@markup.link.label"] = {},
		["@markup.link.url"] = {},
		["@markup.list"] = {},
		["@markup.list.checked"] = {},
		["@markup.list.unchecked"] = {},
		["@markup.math"] = {},
		["@markup.quote"] = {},
		["@markup.raw"] = {},
		["@markup.raw.block"] = {},
		["@markup.strikethrough"] = {},
		["@markup.strong"] = {},
		["@markup.underline"] = {},
		["@module"] = {},
		["@module.builtin"] = {},
		["@number"] = {},
		["@number.float"] = {},
		["@operator"] = {},
		["@property"] = {},
		["@punctuation.bracket"] = {},
		["@punctuation.delimiter"] = {},
		["@punctuation.special"] = {},
		["@string"] = {},
		["@string.documentation"] = {},
		["@string.escape"] = {},
		["@string.regexp"] = {},
		["@string.special"] = {},
		["@string.special.path"] = {},
		["@string.special.symbol"] = {},
		["@string.special.url"] = {},
		["@tag"] = {},
		["@tag.attribute"] = {},
		["@tag.builtin"] = {},
		["@tag.delimiter"] = {},
		["@type"] = {},
		["@type.builtin"] = {},
		["@type.definition"] = {},
		["@variable"] = { fg = colors.silver },
		["@variable.builtin"] = {},
		["@variable.member"] = { link = "Identifier" },
		["@variable.parameter"] = {},
		["@variable.parameter.builtin"] = {},
		-- rainbow_delimiters plugin highlights
		["RainbowDelimiterRed"] = { fg = colors.red },
		["RainbowDelimiterOrange"] = { fg = colors.orange },
		["RainbowDelimiterYellow"] = { fg = colors.yellow },
		["RainbowDelimiterGreen"] = { fg = colors.green },
		["RainbowDelimiterBlue"] = { fg = colors.blue },
		["RainbowDelimiterViolet"] = { fg = colors.purple },
		["RainbowDelimiterCyan"] = { fg = colors.cyan },
		["RainbowDelimiterMagenta"] = { fg = colors.magenta },
	}
	for group, args in pairs(highlights) do
		if next(args) ~= nil then
			vim.api.nvim_set_hl(0, group, args)
		end
	end
end)
