#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 1
bspc config window_gap 5
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config focus_follows_pointer true
bspc config bottom_padding 32

bspc config normal_border_color "#000000"
bspc config active_border_color "#ffaf00"
bspc config focused_border_color "#b2b2b2"
bspc config presel_feedback_color "#b2b2b2"

# window options
bspc rule -a pavucontrol-qt desktop=^10 follow=off -o
bspc rule -a mintupdate desktop=^10 follow=off -o
bspc rule -a blueman desktop=^10 follow=off -o

# startup
feh --bg-fill ~/Pictures/zewltrond.jpg
killall -q picom; picom &
killall -q xfce4-notifyd; /usr/lib/x86_64-linux-gnu/xfce4/notifyd/xfce4-notifyd &
killall -q polkit-gnome-authentication-agent-1; /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
$HOME/.config/polybar/launch.sh
killall -q $HOME/.config/bspwm/notify; $HOME/.config/bspwm/notify 20 90 &
killall -q volumeicon; volumeicon &
killall -q nm-applet; nm-applet &
killall -q blueman-applet; blueman-applet &
killall -q mintupdate; mintupdate &
